import { Component, OnInit } from "@angular/core";
import {
  faChevronLeft,
  faChevronRight,
  faStar,
} from "@fortawesome/free-solid-svg-icons";
import { NgImageSliderComponent } from "ng-image-slider";
import { NgxslickComponent } from "ngx-simple-slick";
import { Product, ProductService } from "src/app/Shared/product.service";
import { CategoryData } from "../../Partials/dropdown/dropdown.component";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent implements OnInit {
  chevronLeft = faChevronLeft;
  chevronRight = faChevronRight;
  iconStar = faStar;
  products: Product[] = [];
  isLoading: boolean = false;
  heroImages: any[] = [
    { thumbImage: "assets/Images/heroSliderImg1.jpg" },
    { thumbImage: "assets/Images/heroSliderImg3.jpg" },
    { thumbImage: "assets/Images/heroSliderImg2.jpg" },
  ];
  data: { name: string; data: string[] }[] = [
    {
      name: "MOST SEARCHED FOR ON FLIPKART:",
      data: [
        "Flipkart Axis Bank Super Elite Credit card",
        "Primebook Laptops",
        "Bounce Infinity E1",
        "Buy Laptop on EMI",
        "Infinix Zero Book Ultra",
        "OPPO Reno8 5G",
        "OPPO Reno8 Pro 5G",
        "Fresh Flower Bouquet",
        "Electric Cycles",
        "Badminton",
        "Bouquet",
        "Oneplus Monitors",
        "Sell Old Mobile Phones",
        "Premium Laptops",
        "Electronics Store",
        "Phone cover",
        "Infinix INBook Y1 Plus",
        "Okaya Electric Vehicles",
        "bgauss electric scooter",
        "OPPO Reno7 Pro 5G",
        "iPhone 13",
        "iPhone 13 Pro",
        "iPhone 13 Pro Max",
        "iPhone 13 Mini",
        "Google Pixel 6a covers",
        "Flipkart Quick",
        "Ampere Magnus",
        "Flipkart Help Centre",
        "Online Boat Store",
        "Covers from Rs 99",
        "Flipkart Track Orders",
        "Flipkart Manage Orders",
        "Flipkart Return Orders",
        "Flipkart Gift Cards Store",
        "Flipkart Axis Bank Credit Card",
        "Flipkart Pay Later",
      ],
    },
    {
      name: "MOBILES:",
      data: [
        "iPhone 12 64GB",
        "iPhone 12 Pro 512GB",
        "iPhone 12 128GB",
        "Vivo Y91i",
        "Vivo Y11",
        "Vivo Y15",
        "Vivo Y50",
        "Vivo Y12",
        "Reno2 F",
        "Oppo A12",
        "Oppo F15",
        "Oppo A31",
        "Samsung A71",
        "Samsung A51",
        "Samsung A31",
        "Realme X2",
        "iPhone 11",
        "iPhone 11 Pro",
        "Mobile Cover",
        "Mobile Offers",
        "iphone x",
        "4G Mobile",
        "Nokia Mobile",
        "Samsung Mobile",
        "iphone",
        "Oppo Mobile",
        "Vivo Mobile",
      ],
    },
    {
      name: "CAMERA:",
      data: [
        "GoPro Action Camera",
        "Nikon Camera",
        "Canon Camera",
        "Sony Camera",
        "Canon DSLR",
        "Nikon DSLR",
      ],
    },
    {
      name: "LAPTOPS:",
      data: [
        "MacBook Pro M2",
        "Premium Laptop",
        "ASUS ROG Strix SCAR 16 (2023) Core i9 13th Gen",
        "ASUS ROG Zephyrus M16 (2023) Core i9 13th Gen",
        "ASUS Zenbook 14 OLED (2022)",
        "Realme Book Prime Core i5 11th Gen",
        "Microsoft Surface Go Pentium 128GB",
        "Branded Laptops",
        "Apple Laptops",
        "Acer Laptops",
        "Lenovo Laptops",
        "Dell Laptops",
        "Asus Laptops",
        "HP Laptops",
        "Gaming Laptops",
        "2 in 1 Laptops",
        "Laptops",
        "Dell latest laptops 2022",
        "HP latest laptops 2022",
        "Infinix INBook Y1 Plus",
        "SAMSUNG Galaxy Book3",
        "12th Gen Intel Core Laptops",
      ],
    },
    {
      name: "TVS:",
      data: [
        "Nokia TV",
        "Panasonic TV",
        "Thomson TV",
        "Vu TV",
        "Realme TV",
        "Motorola TV",
        "OnePlus TVs",
        "LG TV",
        "TV",
        "Sony TV",
        "Samsung TV",
        "Android Television",
        "Iffalcon Tv",
        "Mi TV",
      ],
    },
    {
      name: "LARGE APPLIANCES:",
      data: [
        "TV & Appliances End of Season Sale",
        "Television",
        "Washing Machines",
        "Refrigerators",
        "Air Conditioners",
        "Electric Cookers",
        "Electric Jug(Heater) / Travel Kettles",
        "Induction Cooktops",
        "Inverters / stabilizer",
        "Irons / Iron Box",
        "Mixer Grinder Juicer",
        "Wet Grinders",
        "Chimneys",
        "Microwave Ovens",
        "Vacuum Cleaners",
        "Water Purifier",
        "Fan",
        "MarQ Customer Care",
      ],
    },
    {
      name: "CLOTHING:",
      data: [
        "Men Shirts",
        "Kurta Pajama",
        "Kurtas",
        "Men T-Shirts",
        "Jeans",
        "Saree",
        "Dresses",
        "Kids Dresses",
        "Designer Salwar Suits",
        "Bra",
        "Designer Kurtis",
        "Track Pant",
        "Men Kurtas",
        "Gym Wear",
        "Party Dresses",
        "Palazzo Suits",
        "Boys Clothing",
        "Gloves",
        "Nighty",
        "Maxi Dresses",
        "Anarkali",
        "Gowns",
        "Culottes",
        "Salwar Suits",
        "Kurtis",
        "Designer Sarees",
        "Leggings",
        "Shorts",
        "Georgette Sarees",
        "Ethnic Wear",
        "Briefs & Trunks",
        "Nike Watches",
        "Ascot Tie",
        "Corset Tops Tunics",
        "Leather PU Skirts",
        "Corset tops camisoles",
        "Women magenta earrings",
        "No collar jackets",
        "Green dress material",
        "Black patiala kurta set",
        "Men camel shoes casual",
        "Black pathani",
        "Tassel Sarees",
        "Khaki dresses",
        "Kids formal dresses",
        "Mauve shirts",
        "Women henley",
        "uppada pattu sarees",
        "Leopard dresses",
        "Sleeveless shrugs",
      ],
    },
    {
      name: "FOOTWEAR:",
      data: [
        "Shoes",
        "Adidas Shoes",
        "Reebok Shoes",
        "Nike Shoes",
        "Puma Shoes",
        "Boots",
        "Bata Shoes",
        "Woodland Shoes",
        "Skechers Shoes",
        "Sneakers",
        "Womens Boots",
        "Sports Shoes",
        "Loafers",
        "Sandals",
        "Lotto Sports Shoes",
        "Casual Shoes",
        "Womens Skechers Shoes",
        "Asics Sports Shoes",
        "Formal Shoes",
        "School Shoes",
      ],
    },
    {
      name: "GROCERIES:",
      data: [
        "PhonePe Grocery Voucher",
        "Hand Wash",
        "Soap",
        "Cashew Nuts",
        "Sunflower Oil",
        "Eggs",
        "Toilet Cleaner",
        "Harpic Toilet Cleaner",
        "Dettol Soap",
        "Mustard Oil",
        "Biscuits",
        "Cheese",
        "Patanjali Atta",
        "Fortune Oil",
        "Aashirvaad Atta",
        "Tea",
      ],
    },
    {
      name: "BEST SELLING ON FLIPKART:",
      data: [
        "Fire-Boltt Ninja Calling Pro Bluetooth Calling Smartwatch 1.69 inch HD Display Smartwatch",
        "Best Gas Geyser",
        "Kitchen Geyser",
        "Nutri Blenders",
        "Portable Air Cooler",
        "Best Air Cooler",
        "Bags",
        "Hitachi Refrigerator 3 Door",
        "Books",
        "Toys",
        "Candles",
        "Helmets",
        "Wall Clocks",
        "Baby Food",
        "Chocolates",
        "Cycles",
        "Calculators",
        "Lipsticks",
        "Mask",
        "Vertiv UPS",
        "Fastrack Watches",
        "Wallets",
        "Earrings",
        "Gold Coins",
        "Realme Pad Mini",
        "Handbags",
        "conekt SW2 Smartwatch",
        "Mivi DuoPods a350",
        "Speaker Cleaner",
      ],
    },
    {
      name: "FURNITURE:",
      data: [
        "Furniture",
        "Sofas",
        "Beds",
        "Dining sets",
        "Wardrobes",
        "Mattresses",
        "TV Units",
        "Tables",
        "Chairs",
        "Shelves",
        "Bean Bags",
        "Office Chairs",
        "Computer Table",
        "Office Tables",
        "Red Sofa",
        "Wakefit Beds",
        "White Sofa",
        "Wakefit Mattress",
        "Green Sofa",
        "Black Sofa",
        "Brown Sofa",
      ],
    },
    {
      name: "BGMH:",
      data: [
        "Whey Protein",
        "Homeopathy",
        "Cricket",
        "Cycles",
        "Footballs",
        "Treadmills",
        "Christmas Gifts",
        "Fitness Accessories",
        "Online Guitar",
        "Books Store",
        "Musical Instrument Store",
        "Dabur Chyawanprash",
        "Baidyanath Chyawanprash",
        "Energy Drinks",
        "Toys",
        "Milk Drink Mixes",
        "Rakhi",
        "Chyawanprash",
        "Indian Flag",
        "Protein Supplements",
      ],
    },
  ];

  dataDropdownFashion: CategoryData[] = [
    {
      name: "Men's Top Wear",
      subCategories: [
        "All",
        "Men's T-Shirts",
        "Men's Casual Shirts",
        "Men's Formal Shirts",
        "Men's Kurtas",
        "Men's Ethnic Sets",
        "Men's Blazers",
        "Men's Raincoat",
        "Men's Windcheaters",
        "Men's Suit",
        "Men's Fabrics",
      ],
    },
    {
      name: "Men's Bottom Wear",
      subCategories: [
        "All",
        "Men's Jeans",
        "Men's Trousers",
        "Men's Trackpants",
        "Men's Shorts",
        "Men's Cargos",
        "Men's Threefourths",
        "Men's Pyjamas & Loungepants",
        "Men's Dhoti",
        "Men's Ethnic Pyjama",
      ],
    },
    {
      name: "Women Ethnic",
      subCategories: [
        "All",
        "Women Sarees",
        "Women Kurtas & Kurties",
        "Women Kurta Sets & Salwar Suits",
        "Ethnic Dresses",
        "Women Dress Materials",
        "Women Gowns",
        "Women Lehenga Cholis",
        "Women Leggings & Patialas",
        "Women Palazzos & Shararas",
        "Women Blouse",
        "Women Dupatta",
      ],
    },
    {
      name: "Women Western",
      subCategories: [
        "All",
        "Women Tops",
        "Women Dresses",
        "Women T-Shirts & Polo T-Shirts",
        "Wemen Jeans",
        "Women Nighties & Night Dresses",
        "Women Nightsuit",
        "Women Track Pants",
        "Women Trouser",
        "Women Jumpsuit",
        "Women Shapewear",
        "Women Sports Bra",
      ],
    },
    {
      name: "Men Footwear",
      subCategories: [
        "All",
        "Men's Sports Shoes",
        "Men's Casual Shoes",
        "Men's Sandals & Floaters",
        "Men's Slippers & Flip Flops",
        "Men's Formal Shoes",
        "Men's Ethnic Shoes",
        "Active Footwear",
        "Combo Footwear",
        "Shoe Care",
      ],
    },
    {
      name: "Women Footwear",
      subCategories: [
        "All",
        "Women Flats",
        "Women Heels",
        "Women Wedges",
        "Women Slipper Flip Flops",
        "Women Casual Shoes",
        "Women Sports Shoes",
        "Women Ballerinas",
        "Women Ethnic Shoes",
        "Women Sneakers",
        "Women Walking Shoes",
        "Women Boots",
      ],
    },
    {
      name: "Watches and Accessories",
      subCategories: [
        "Men & Women Watches",
        "Men & Women Sunglasses",
        "Wallets",
        "Men & Women Belts",
        "Women Fashion Jewellery",
        "Men Fashion Jewellery",
        "Precious Jewellery",
        "Precious Coins & Bars",
        "Precious Articles",
        "Frames & Contact Lenses",
        "Kids Accessories",
      ],
    },
    {
      name: "Bags, Suitcases & Luggage",
      subCategories: [
        "All",
        "Bags & Backpacks",
        "Suitcases & Trolleys",
        "Dufflebags",
        "Rucksacks",
        "Handbags",
        "Slingbags",
        "Women's Clutches & Wallets",
        "Messenger Bags",
        "Travel Accessories",
      ],
    },
    {
      name: "Kids",
      subCategories: [
        "All",
        "Girls Dresses",
        "Boys & Girls Tshirts",
        "Boys & Girls Combosets",
        "Boys & Girls Ethnic Wear",
        "Boys & Girls Jeans",
        "Boys & Girls Shorts",
        "Boys & Girls Trackpants",
        "Boys & Girls Innerwear",
        "Infant Wear",
        "Kids Slipper Flip Flops",
        "Kids Sports Shoes",
      ],
    },
    {
      name: "Essentials",
      subCategories: [
        "Men's Briefs & Trunks",
        "Men's Vests",
        "Men's Boxers",
        "Women Lingerie Sets",
        "Women Bra",
        "Women Panty",
        "Women Sarees",
        "Women Kurtas",
        "Women Kurta Sets & Salwar Suits",
        "Boys Innerwear",
        "Boys Innerwear",
        "Girls Innerwear",
        "Women Slipper Flip Flops",
      ],
    },
    {
      name: "Winter",
      subCategories: [
        "All",
        "Men's Jackets",
        "Men's Sweatshirts",
        "Men's Sweaters",
        "Men's Thermals",
        "Women's Jackets",
        "Women's Sweatshirts",
        "Women's Sweaters & Cardigans",
        "Women's Shrugs",
        "Kids SweatShirts",
        "Women Kurtas",
        "Kids Jackets",
      ],
    },
  ];

  dataDropDownElectronics: CategoryData[] = [
    {
      name: "Audio",
      subCategories: [
        "All",
        "Bluetooth Headphones",
        "Wired Headphones",
        "True Wireless Earbuds",
        "Bluetooth Speakers",
        "Soundbars",
        "Home Theatres",
        "TV Streaming Device",
        "Remote Control",
        "DTH Set top box",
        "Headphones Pouch & Case Covers",
      ],
    },
    {
      name: "Electronics GST Store",
      subCategories: [],
    },
    {
      name: "Cameras & Accessories",
      subCategories: [
        "All",
        "DSLR & Mirrorless",
        "Sports & action",
        "Point & Shoot",
        "Instant Cameras",
        "Camcorders",
        "Camera tripods",
        "Camera Lenses",
        "Drone",
        "Flashes",
        "Gimbals",
        "Binoculars",
        "Other Camera Accessories",
      ],
    },
    {
      name: "Computer Peripherals",
      subCategories: [
        "All",
        "Printers",
        "Monitors",
        "Projectors",
        "Portable Projectors",
        "Toners",
        "Ink Cartridges",
        "Ink Bottles",
        "Receipt Printers",
        "Lamination Machines",
        "Note Counting Machines",
        "Barcode Scanners",
        "Currency Detectors",
      ],
    },
    {
      name: "Gaming",
      subCategories: [
        "All",
        "Gaming Consoles",
        "Gaming Mouse",
        "Gaming Keyboards",
        "Gamepads",
        "Games",
        "Accessory Kits",
        "Gaming Accessories Combo",
        "Gaming Mousepads",
        "Membership Cards",
        "Controllers",
        "Other Gaming Accessories",
        "Gaming Components",
      ],
    },
    {
      name: "Health & Personal Care",
      subCategories: [
        "All",
        "Trimmers",
        "Shavers",
        "Hair Straighteners",
        "Hair Dryers",
        "Epilators",
        "Glucometers And Accessories",
        "Blood Pressure Monitors",
        "Digital Thermometers",
        "Weighing Scales",
        "Massagers",
        "Nebulizers",
        "Vaporizers",
      ],
    },
    {
      name: "Laptop Accessories",
      subCategories: [
        "All",
        "Mouse",
        "Laptop Keyboards",
        "Router",
        "Data Cards",
        "UPS",
        "USB Gadgets",
        "Security Software",
        "Laptop Battery",
        "Laptop Adapter",
        "Wireless USB Adapter",
        "Processor",
        "Other Accessories",
      ],
    },
    {
      name: "Laptop and Desktop",
      subCategories: [
        "All",
        "Laptops",
        "Gaming Laptops",
        "Desktop PCs",
        "All In One PCs",
        "Mini PCs",
        "Tower PCs",
        "PC Finder",
        "GST Invoice on Laptops",
        "Laptop Buying Guide",
      ],
    },
    {
      name: "MobileAccessory",
      subCategories: [
        "All",
        "Plain Cases",
        "Designer Cases",
        "Screen Guards",
        "Camera Lens Protectors",
        "Tablet Accessories",
        "MobileCable",
        "MobileChargingMobileCharger",
        "MobilePouches",
        "MobileFlash",
        "MobileHolder",
        "MobileUSBGadget",
        "Mobiles Accessories Combos",
      ],
    },
    {
      name: "Powerbank",
      subCategories: ["All", "Powerbank"],
    },
    {
      name: "Smart Home automation",
      subCategories: [
        "All",
        "Smart Assistants",
        "Smart Lights",
        "Smart Cameras",
        "Smart Switches",
        "Smart Door locks",
        "Sensors & Alarms",
      ],
    },
    {
      name: "Smart Wearables",
      subCategories: ["All", "Smart Watches", "Smart Bands", "Smart Glasses"],
    },
    {
      name: "Storage",
      subCategories: [
        "All",
        "MobileMemoryCard",
        "ComputerStoragePendrive",
        "MobileStoragePendrive",
        "ExternalHardDrive",
        "InternalHardDrive",
      ],
    },
    {
      name: "Tablets",
      subCategories: [
        "All",
        "Tablets With Call Facility",
        "Tablets Without Call Facility",
      ],
    },
  ];

  dataDropDownHome: CategoryData[] = [
    {
      name: "Home Furnishings",
      subCategories: [
        "All",
        "Bed Linens",
        "Bedsheets",
        "Blankets",
        "Curtains & Accessories",
        "Bath linen",
        "Floor coverings",
        "Covers & protectors",
        "Cushions & Pillows",
        "Kitchen Linen Sets",
        "Table Linen Sets",
        "Sofa & curtain fabrics",
        "Branded Collections",
      ],
    },
    {
      name: "Furniture Studio",
      subCategories: [],
    },
    {
      name: "Living Room Furniture",
      subCategories: [
        "All",
        "Sofas Sets & Sectionals",
        "TV Units",
        "Dining Sets",
        "Coffee Tables",
        "Sofa Beds",
        "Recliners",
        "Living Room Chairs",
        "Cabinet & Drawers",
        "Bookshelves",
        "Shoe Racks",
        "Office Tables",
        "Office Chairs",
      ],
    },
    {
      name: "Kitchen & Dining",
      subCategories: [
        "All",
        "Cookware",
        "Lunchboxes, Bottles & Flasks",
        "Knives, Choppers & Cutters",
        "Gas Stoves & Accessories",
        "Kitchen tools",
        "Tableware & Dinnerware",
        "Containers & Kitchen Storage",
        "Barware",
        "Bakeware",
        "Handjuicers & Grinders",
        "Disposable Supplies",
        "Outdoor cooking",
      ],
    },
    {
      name: "Bedroom Furniture",
      subCategories: [
        "All",
        "Mattresses",
        "Beds",
        "Wardrobes",
        "Side Tables",
        "TV Units",
        "Office Tables",
        "Office Chairs",
        "Bookshelves",
        "Bar Cabinets",
        "Bar Stools",
        "Rocking Chairs",
        "Benches",
      ],
    },
    {
      name: "Home Decor",
      subCategories: [
        "All",
        "Lightings",
        "Stickers & Wallpapers",
        "Paintings & Posters",
        "Clocks",
        "Showpieces & Decoratives",
        "Wall Decor",
        "Flowers & Vases",
        "Home Fragrances",
        "Windchimes & Dream catcher",
        "Photo frames & Albums",
        "Diyas, Candles & Holders",
        "Festive & Giftng",
      ],
    },
    {
      name: "Tools & Utility",
      subCategories: [
        "All",
        "Hand tools",
        "Power Tools",
        "Measuring Tools",
        "Home Storage & Organizers",
        "Umbrellas",
        "Appliance Trolley & Stands",
        "Cloth Dryer Stand",
        "Appliance Filter & Cartridges",
        "Laundary Organization",
        "Lock & Security",
        "Fire & Personal Safety",
        "Paint Supplies & Equipments",
      ],
    },
    {
      name: "Work Space Furniture",
      subCategories: [],
    },
    {
      name: "Lightings & Electricals",
      subCategories: [
        "All",
        "Bulbs",
        "Emergency Lights",
        "Torches",
        "Tubelights",
        "Extension Cords",
        "Outdoor Lamps",
        "Batteries",
        "ElectricalWire",
        "ElectricalSocket",
        "ElectricDoorBell",
        "Solar Lights, Panels & Batteries",
        "Electrical Hardware",
      ],
    },
    {
      name: "Space Saving Furniture",
      subCategories: [
        "All",
        "Portable Laptop Tables",
        "Collapsible Wardrobes",
        "Bean Bags & Covers",
        "Shoe Racks",
        "Cabinet Drawers",
        "Inflatable Sofas",
        "Hammock Swings",
        "Home Temples",
        "Bookshelves",
        "TV Mounts",
        "Kitchen Trolley",
        "Kitchen Cabinet",
      ],
    },
    {
      name: "Cleaning & Bath",
      subCategories: [
        "All",
        "Mops",
        "Cleaning Supplies",
        "House Hold supplies",
        "Air Fresheners",
        "Cleaning Gloves",
        "Liquid Detergents",
        "Taps & Faucet",
        "Toothbrush holder",
        "Bathroom Rack & Shelves",
        "Shower Heads",
        "Bath & Kitchen Fittings",
        "Bathroom Accesorries",
      ],
    },
    {
      name: "Kids Furniture",
      subCategories: [
        "All",
        "Bunk Beds",
        "Kids' Seating",
        "Kids' Table",
        "Kids' Chairs",
        "Kids' Sofas",
        "Bookshelves",
        "Chest of Drawers",
        "Cupboards",
        "Shoe Racks",
        "Kids' Bean Bags",
        "Portable Pool",
        "Sofa Beds",
      ],
    },
    {
      name: "Pet & Gardening",
      subCategories: [
        "All",
        "Plant Seeds",
        "Soil Manure",
        "Pots & Planters",
        "Plant & Planters",
        "garden tool set",
        "watering Equipments",
        "Dog Essentials",
        "Cat Essentials",
        "Fish & Aquatic",
        "Pet Grooming & Hygiene",
        "Pet Toys",
        "Pet Health & Safety",
      ],
    },
  ];

  dataDropDownBeauty: CategoryData[] = [
    {
      name: "Beauty & Personal Care",
      subCategories: [
        "View All",
        "Bath & Oral Care",
        "Personal Hygiene",
        "Eye Makeup",
        "Face Makeup",
        "Lip Makeup",
        "Hair Care",
        "Bath Essentials",
        "Women's Personal Hygiene",
        "Body & Skin Care",
        "Luxury",
        "Top Brand Deals",
      ],
    },
    {
      name: "Men's Grooming",
      subCategories: [
        "View All",
        "Face Washes",
        "Beard Oils",
        "Hair Styling",
        "Shaving Essentials",
        "Aftershave",
        "Face Creams & Face Packs",
        "Soaps & Bodywashes",
        "Men's Grooming Combos",
        "Sexual Wellness",
      ],
    },
    {
      name: "Food & Drinks",
      subCategories: [
        "View All",
        "Beverages",
        "Nuts & Dry Fruits",
        "Cooking Essentials",
        "Breakfast Items",
        "Snacks Corner",
        "Jams, spreads & Honey",
        "Ready to Cook & Eat",
        "Chocolates",
        "Baking Essentials",
        "Sweets Store",
        "Top Brand Deals",
      ],
    },
    {
      name: "Nutrition & Health Care",
      subCategories: [
        "View All",
        "Masks",
        "Ayurvedic Supplements",
        "Health Drinks",
        "Vitamin Supplements",
        "Protein Supplements",
        "Women's Safety",
        "Home Medicines",
        "Home Medical Supplies",
        "Healthcare Comos",
        "Professional Medical Supplies",
        "Top Brand Deals",
      ],
    },
    {
      name: "Baby Care",
      subCategories: [
        "View All",
        "Baby Diapers",
        "Baby Wipes",
        "Baby Bath & Grooming",
        "Baby Gift Sets & Combo",
        "Baby Medical & Health Care",
        "Nursing & Breast Feeding",
        "Feeding Bottles, Utensils & Accessories",
        "Baby Food",
        "Baby Bedding",
        "Baby Gear",
        "Top Brand Deals",
      ],
    },
    {
      name: "Toys & School Supplies",
      subCategories: [
        "View All",
        "Remote Control Toys",
        "Soft Toys",
        "Puzzles",
        "Board Games",
        "Learning & Educational Toys",
        "Cars & Die-Cast Vehicles",
        "Baby Toys",
        "Gifting Toys",
        "School Bags & Backpacks",
        "School Supplies",
        "Top Brand Deals",
      ],
    },
    {
      name: "Sports & Fitness",
      subCategories: [
        "View All",
        "Badminton",
        "Cricket",
        "Cycling",
        "Football",
        "Fitness Equipments",
        "Supports",
        "Shakers & Sippers",
        "Gym Gloves",
        "Dumbbells",
        "Yoga",
        "Top Brand Deals",
      ],
    },
    {
      name: "Books",
      subCategories: [
        "View All",
        "Test prep",
        "Academics",
        "Literature & Fiction",
        "Non Fiction",
        "Young Readers",
        "Audio Books",
        "Indian Languages",
        "Acoustic Guitars",
        "Musical keyboards",
        "Microphones",
        "Stage Equipment & Accessories",
      ],
    },
    {
      name: "Music",
      subCategories: [
        "Musical Instruments",
        "Music & Tv Shows",
        "Acoustic Guitars",
        "Keys and Synthesizer",
        "Microphones",
        "Studio and Stage equipment",
        "String Instruments",
        "Indian instruments",
        "Wind instruments",
      ],
    },
    {
      name: "Stationery & Office Supplies",
      subCategories: [
        "View All",
        "Pens & Gift Sets",
        "Notebooks & Diaries",
        "Art Supplies",
        "Calculators",
        "Keychains",
        "Card Holders",
        "Desk Organizers",
        "Office Supplies",
        "Office Equipments",
        "Party Supplies",
        "Top Brand Deals",
      ],
    },
    {
      name: "Auto Accessories",
      subCategories: [
        "View All",
        "Bike Essentials",
        "Car & Bike Covers",
        "CarAirFreshener",
        "CarBluetoothDevice",
        "CarLubricant",
        "CarVacuumCleaner",
        "CarMediaPlayer",
        "Helmet",
        "Vehicle Washing & Cleaning Products",
        "Tyres",
        "Top Brand Deals",
      ],
    },
    {
      name: "Safety & Hygiene Essentials",
      subCategories: [
        "View All",
        "Masks",
        "Sanitizers",
        "Hand Wash",
        "Gloves",
        "PPE Kits",
        "Face Shields",
        "UV Sterilizer Box",
        "Safety Goggles",
        "Vitamins for Immunity",
      ],
    },
  ];

  dataDropDownTwoWheelers: CategoryData[] = [
    {
      name: "Petrol Vehicles",
      subCategories: [],
    },
    {
      name: "Electric Vehicles",
      subCategories: [],
    },
  ];

  constructor(private productService: ProductService) {}

  async ngOnInit(): Promise<void> {
    this.isLoading = true;
    const newProducts = await this.productService.getAllProducts();
    this.products = newProducts;
    this.isLoading = false;
  }

  getProductsByCategory(category: "electronics" | "beauty"): Product[] {
    let filtered = [
      ...this.products.filter(
        (product: Product) => product.category === category
      ),
    ];
    return filtered;
  }

  slideImage(slider: NgImageSliderComponent, move: "next" | "prev"): void {
    if (move === "next") {
      slider.next();
    } else {
      slider.prev();
    }
  }

  slidePrev(slider: NgxslickComponent) {
    slider.showPrev();
  }
  slideNext(slider: NgxslickComponent) {
    slider.showNext();
    console.log(slider);
  }
}
